### ISSUE TITLE
Error raised on closing a text editor when the mouse is over the minimap

### ISSUE THREAD

**Issue by abe33** [olmokramer/atom-minimap-codeglance#11]
Initially reported in atom-minimap/minimap#380

And here's a capture of the error, there's two side to the problem, when there's another editor in the pane, the error is raised, but when there's only one there's no error but the code glance view persist in the pane: 
![codeglance](https://cloud.githubusercontent.com/assets/247140/9548699/43577bcc-4da2-11e5-911c-34806e13d599.gif)

My guess is that the `mouseleave` event isn't triggered when the element is destroyed, and `mouseenter` not triggered on the minimap element below which lead the `mousemove` handler to operate on the destroyed minimap instead.

Let me know if you think there's a need for a change in the minimap API.

**Comment by olmokramer** [comment]
Thanks for taking the time to write the report and investigate! I don't think there's need to change the API, I can just dispose of everything on `textEditor.onDidDestroy` I think. I'll investigate a bit more and report back.

**Comment by olmokramer** [comment]
Aha, so the problem was actually that `mouseenter` is never triggered on the _second_ minimap, so `setCurrentMinimap` is never called. It tries to access the `textEditor` on the first minimap, which doesn't exist anymore... Fixed it by adding a check in the `mousemove` event.
