### ISSUE TITLE
Codeglance takes up 100% of screen height and only shows the top of the file

### ISSUE THREAD

**Issue by sbrl** [olmokramer/atom-minimap-codeglance#27]
![image](https://cloud.githubusercontent.com/assets/9929737/19341170/4c2cce34-9124-11e6-9de7-40e50fe7fcdc.png)

The codeglance appears to be way too tall and only shows the top of the file. In the above image I have a border set around the codeglance so you can see the edges.

**Comment by rmvermeulen** [comment]
I have the exact same issue. Got a new pc, just reinstalled the atom packages.
Issue persist if I disable all but minimap + codeglance + core packages.

**Comment by sbrl** [comment]
I'm glad I'm not the only one with this issue! I think codeglance updated recently and I suspect that it's that causing the issue.

**Comment by sergio-faraldo** [comment]
Same issue here. It was fine until about two days ago.

**Comment by ghost** [comment]
Same here. I have uninstalled and reinstalled the package, but nothing changed

**Comment by sergio-faraldo** [comment]
The issue is only present on my Windows 10 install of atom, not on the Linux VBox I have on the same computer.

**Comment by ghost** [comment]
I have this issue since I updated to Atom 1.11.2 (on Ubuntu).
The border (on the top and right) is displayed correctly, but the content claimes the whole screen.

**Comment by petKitsune** [comment]
same on win7x64 after update Atom to 1.11.2

**Comment by ArpitKumarGahlot** [comment]
Facing similar issue on openSuse Tumbleweed. This occurred in past week after update. I am on:
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by rugk** [comment]
I am experiencing the same issue. Just updated to Atom 1.11 - it might be related to this.
The "height" option is completely ignored.

Linux x64

**Comment by coltjones** [comment]
Same issue here on OS X 
Atom 1.11.2
minimap 4.25.6
minimap-codegalnce 0.4.5

**Comment by ulope** [comment]
Also reporting in with the same problem:
- macOS 10.11.6
- Atom 1.11.2
- minimap 4.25.6
- minimap-codeglance 0.4.5

**Comment by brahmcapoor** [comment]
Same problem: 
- macOS 10.12
- Atom 1.11.2
- minimap 4.26.1
- minimap-codeglance 0.4.5

**Comment by hookdump** [comment]
Same problem:
- OS X 10.12
- Atom 1.11.2
- minimap 4.25.6
- minimap-codeglance 0.4.5

Will try to find a solution this weekend. D:

**Comment by DZetaDev** [comment]
I have found a possible solution :wrench: .
In `atom-minimap-codeglance/lib/minimap-codeglance-element.js`
In the **updateDimensions** add `this.lines.setHeight(this.clientHeight)` at the end.

``` javascript
updateDimensions() {
    var lineHeight = this.lines.getLineHeightInPixels() ||
      atom.workspace.getActiveTextEditor().getLineHeightInPixels()
    this.style.height = `${config.numberOfLines * lineHeight}px`
    this.lines.setHeight(this.clientHeight)
}
```

**Comment by petKitsune** [comment]
works for me
thx

win7x64
Atom 1.11.2 + 1.12.0
minimap 4.25.6
minimap-codeglance 0.4.5

**Comment by rmvermeulen** [comment]
I wanted to try that fix, but the issue had apparently already gone away. Maybe one of the later atom updates fixes this

**Comment by petKitsune** [comment]
@axit-rasmus 

I can confirm this on Atom 1.12.0
Atom 1.11.02 still need the extra line

**Comment by sbrl** [comment]
Yep, atom 1.12.0 fixes this issue. I think that this package might be developed against atom beta and not atom stable.

**Comment by ghost** [comment]
Atom 1.12.0 fixes the issue for me
