### ISSUE TITLE
Deprecated selector in `minimap-codeglance\styles\minimap-codeglance.atom-text-editor.less`

### ISSUE THREAD

**Issue by MatthiasF999** [olmokramer/atom-minimap-codeglance#28]
In `minimap-codeglance\styles\minimap-codeglance.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `minimap-codeglance atom-text-editor::shadow .cursor,
minimap-codeglance atom-text-editor::shadow ::-webkit-scrollbar` => `minimap-codeglance atom-text-editor.editor .cursor,
minimap-codeglance atom-text-editor.editor ::-webkit-scrollbar`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by piaoyidage** [comment]
Me too.How to solve this problem?

**Comment by alumni** [comment]
Pull request #32 would solve this issue.

As an alternative, you can replace the `&::shadow` selector with `&.editor` in `minimap-codeglance/styles/minimap-codeglance.atom-text-editor.less` instead.

**Comment by forestgagnon** [comment]
Is this repo maintained anymore?

**Comment by cnsumner** [comment]
Doesn't appear so...  I've made a new issue (#34) for some discussion on what we can do about that.

**Comment by davisonio** [comment]
Merged #32 which fixed this ;) Will be available in next version.
