### ISSUE TITLE
Deprecated selector in `minimap-codeglance/styles/minimap-codeglance.atom-text-editor.less`

### ISSUE THREAD

**Issue by forestgagnon** [olmokramer/atom-minimap-codeglance#30]
In `minimap-codeglance/styles/minimap-codeglance.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `minimap-codeglance atom-text-editor::shadow .cursor,
minimap-codeglance atom-text-editor::shadow ::-webkit-scrollbar` => `minimap-codeglance atom-text-editor.editor .cursor,
minimap-codeglance atom-text-editor.editor ::-webkit-scrollbar`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by pwagland** [comment]
I'm still seeing this issue with atom 1.13.0, and code glance 0.4.5, has this been fixed and/or will it be fixed?

**Comment by forestgagnon** [comment]
I closed this because it was a duplicate of #28
