### ISSUE TITLE
Repo not maintained anymore?

### ISSUE THREAD

**Issue by cnsumner** [olmokramer/atom-minimap-codeglance#34]
The last commit was on Nov 11, 2015.  There's currently two pull requests sitting there unapproved, haven't seen any comments from the owner.

Should we try to contact @olmokramer, and if we can't get a response, try moving active development to another fork and see if we can republish it on the atom packages site?

I'm just beginning to learn electron and atom development, so my contributions would be minimal for the time being, but I can volunteer my fork seeing as I'm active and know enough to at least approve pull requests.  This is a pretty important addon to me.

**Comment by GeorgeWL** [comment]
I think best practice is to:
1. Contact the main dev in whatever way possible
1. Give a bit of time for them to respond.

A: They don't respond within a bit
1. Fork our own
1. Republish it with a different name on Atom Packages.

B: They respond and either:
1. Set additional Admins to Approve
1. Carry on Developing

**Comment by GitSquared** [comment]
Did anyone contact @olmokramer yet? How about we just publish a fork now. It's been a while.

**Comment by davisonio** [comment]
I've contacted and got a response:

> Hi Craig,

>Thanks for your inquiry about my codeglance package! Unfortunately I've been insanely busy the past year, and haven't been able to attend to my Atom packages or GitHub in general.  Also, I have moved to another editor, so I can't really test the packages I've written anymore, let alone provide support for it. I've been meaning to post an announcement, but other stuff has kept me busy and forgetting about that. I'm sorry for the inconvenience.

>I've already added you as a collaborator, but I'd be happy to transfer the entire repository to your account, as it's very unlikely that I'll be using Atom in the distant future. Please let me know if you're okay with that. All I ask is that you keep my commits in the package history :)

>Cheers,
>Olmo

I'll be able to update this repository in the next few days to hopefully get the deprecated bugs fixed and publish this to the atom.io repository. I can also check out these pull requests after some testing. :)

**Comment by GitSquared** [comment]
@davisonio Awesome!

**Comment by pwagland** [comment]
Hi @davisonio , how is it going with this? I landed here today after getting the deprecation warning in Atom :-)

**Comment by jcmarchi** [comment]
@davisonio, did you get the repo control? Need any help with it?

Let's keep the rocks rolling... ;)

**Comment by davisonio** [comment]
> @davisonio, did you get the repo control? Need any help with it?
> 
> Let's keep the rocks rolling... ;)

Hey sorry for the delay, everything's good :)

I've just reviewed the two pull requests and the deprecation problem is now fixed.

I've also published this at atom.io so you should get an update in your text editor :)

The easiest way to help would be to go through some of these issues and try find out how to resolve them!

If anyone would like to submit a PR I would happily review and merge if it's good.
