### ISSUE TITLE
Added Editor Overlay

### ISSUE THREAD

**Issue by round** [olmokramer/atom-minimap-codeglance#40]
Hacked some styles to add an 'overlay' like fade over the editor view:

![image](https://user-images.githubusercontent.com/2340336/30517147-c8771210-9b23-11e7-844a-f71078e56679.png)

```
minimap-codeglance {
  transition: opacity .1s linear;
  backface-visibility: hidden;
  border-top: 1px solid black;
  border-bottom: 1px solid black;
  &:before, &:after {
    position: absolute;
    content: '';
    width: 100%;
    height: 50vh;
    background: linear-gradient(rgba(0,0,0,.66), rgba(33,33,33,0));
    top: 100%;
    left: 0;
    display: block;
  }
  &:after {
    background: linear-gradient(rgba(33,33,33,0), rgba(0,0,0,.66));
    bottom: 100%;
    left: 0;
    top: unset;
  }
}
```

Hopefully this could be useful to someone! Thanks for the amazing package.

**Comment by olmokramer** [comment]
Hi @round, I'm sorry for the extremely late reply. As you have probably noticed I've stopped maintaining my Atom plugins a few years ago. I got very frustrated with how Atom was maintained and started ignoring all of my plugins. I'm sorry for that. I won't install Atom to test and mergeer PRs, but I'd be happy to transfer my repositories to anyone that wants to maintain any of my plugins. Again, I'm sorry.

**Comment by round** [comment]
No apology needed! I still use this plugin regularly and thank you for having made it in the first place, @olmokramer 🙌

**Comment by olmokramer** [comment]
That was a fast reply ;) Thanks for understanding, and I do hope someone steps up!

**Comment by olmokramer** [comment]
PS: I'm reopening this, so if someone does pick this up it won't go unnoticed :)
