### ISSUE TITLE
Overlay is blurry

### ISSUE THREAD

**Issue by eiszfuchs** [olmokramer/atom-minimap-codeglance#7]
Often, the overlay is positioned half a pixel off, so it displays blurry and hard to read.
This can be fixed by **adding**

``` javascript
offsetY = Math.round(offsetY);
```

right **after**

``` javascript
offsetY -= this.clientHeight / 2;
```

in `translateY(offsetY)` of `minimap-codeglance-element.js`. :+1:

**Comment by olmokramer** [comment]
Thanks for letting me know! :+1: Never noticed this myself, maybe I just don't pay much attention :p. I'll put a patch up in a few minutes :)

**Comment by olmokramer** [comment]
Ok I just published the new version. Let me know if it works

**Comment by eiszfuchs** [comment]
Yeah, that works! :+1: 
For everyone else: You have to restart Atom after updating.

(Oh, by the way, the cause is - of course - dividing by `2`.)

**Comment by olmokramer** [comment]
Cool! Thanks for the tip :)
